<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpmailer/src/Exception.php';
require 'phpmailer/src/PHPMailer.php';
require 'phpmailer/src/SMTP.php';

session_start();
require_once('functions.php');


if (isset($_POST['btnsubmit'])) {

  require_once("controllerClass.php");
  $sc = new controllerClass();

  $sc->setname($_POST['name']);
  $sc->setusername($_POST['username']);
  $sc->setemail($_POST['email']);
  $sc->setcompany($_POST['company']);
  $sc->setdepartment($_POST['department']);
  $sc->setdate_request($_POST['daterequested']);
  $sc->setremarks($_POST['otherValue'] . " - " . $_POST['remarks']);
  $sc->setimage($_FILES['file']['name']);
  $sc->setstatus($_POST['status'] = 'Pending');



  $filename = $_FILES["file"]["name"];
  $tempname = $_FILES["file"]["tmp_name"];
  $folder = "../upload/" . $filename;
  move_uploaded_file($tempname, $folder);


  // echo "<script> alert('data saved successfully');document.location='../formRequest.php'</script>";
  $test = $sc->insertData();

  $rqt = new logsController();
  $rqt->setusername($_SESSION['username'] .
    $rqt->setaction('Request Submitting - Description: ' .
      $sc->getremarks()));

  $rqt->insertActionLogs();


  if (!$test) {

    $mail = new PHPMailer(true);


    //Server settings
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';

    $mail->SMTPAuth = true;
    $mail->Username = 'gabolivares63@gmail.com';
    $mail->Password = 'vtjoafhiihdyrfsy';
    // $mail->Username = 'junrey.exelpack@gmail.com';
    // $mail->Password = 'gjtyytiqtuduucwb';
    $mail->SMTPOptions = array(
      'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
      )
    );
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;

    //Send Email
    $mail->setFrom('gabolivares63@gmail.com', 'Maintenance EMC Team');

    //Recipients
    $mail->addAddress('gabolivares63@gmail.com');
    $mail->addReplyTo($sc->getemail($_POST['email']));


    //Content
    $mail->isHTML(true);
    $mail->Subject = $subject = "Employee: " . $sc->getname($_POST['name']) . " from " . $sc->getcompany($_POST['company']);
    $mail->Body = $message = "<img src='https://loader.exel-portal.com/Empwaving.gif' height='200'>
				<br>You Have New Request" . $sc->setremarks($_POST['remarks']) . ", Check Your System to View The Request.<br>Link: <a hreF='https://mtcsystems.exel-portal.com'>mtcsystems.com</a><br>
			    <br><p style='color:red;'><b>This Email is Auto Generated By The System.</b></p>";
    $mail->send();




    // 			   $_SESSION['result'] = 'Message has been sent';
    // 			   $_SESSION['status'] = 'ok';

    // 			echo "send";
    // header("location: index.php");


    flash("msg3", "Successfully Send Request!");

    header("Location:../formRequest.php");
    //    $sc->insertData();

  } else {


    flash("msg4", "Error Send Request!");

    header("Location:../formRequest.php");
  }
}
